In [ ]:
import pandas as pd

In [ ]:
new_data = {'name': ['ahmed', 'ali', 'mona'],
            'age': [20, 22, 19],
            'country': ['egypt', 'Iraq', 'Sudan']}

df = pd.DataFrame(new_data)
df

    name  age country
0  ahmed   20   egypt
1    ali   22    Iraq
2   mona   19   Sudan

In [ ]:
x= pd.Series(data= new_data, index= ['name', 'age', 'country'])
x

name         [ahmed, ali, mona]
age                [20, 22, 19]
country    [egypt, Iraq, Sudan]
dtype: object

In [ ]:
#read the data
df = pd.read_csv('/content/diabetes.csv')
df.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35.0,0,33.6,0.627,50,1
1,1,85,66,29.0,0,26.6,0.351,31,0
2,8,183,64,0.0,0,23.3,0.672,32,1
3,1,89,66,23.0,94,28.1,0.167,21,0
4,0,137,40,35.0,168,43.1,2.288,33,1
5,5,116,74,NaN,0,25.6,0.201,30,0
6,3,78,50,32.0,88,31.0,0.248,26,1
7,10,115,0,0.0,0,35.3,0.134,29,0
8,2,197,70,45.0,543,30.5,0.158,53,1
9,8,125,96,0.0,0,NaN,0.232,54,1

In [ ]:
df.shape

(772, 9)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 772 entries, 0 to 771
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               772 non-null    int64
 1   Glucose                   772 non-null    int64
 2   BloodPressure             772 non-null    int64
 3   SkinThickness             770 non-null    float64
 4   Insulin                   772 non-null    int64
 5   BMI                       765 non-null    float64
 6   DiabetesPedigreeFunction  772 non-null    float64
 7   Age                       772 non-null    int64
 8   Outcome                   772 non-null    int64
dtypes: float64(3), int64(6)
memory usage: 54.4 KB

In [ ]:
df.describe().round()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,772.0,772.0,772.0,770.0,772.0,765.0,772.0,772.0,772.0
mean,4.0,121.0,69.0,21.0,79.0,32.0,0.0,33.0,0.0
std,3.0,32.0,19.0,16.0,115.0,8.0,0.0,12.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0
25%,1.0,99.0,62.0,0.0,0.0,27.0,0.0,24.0,0.0
50%,3.0,117.0,72.0,23.0,24.0,32.0,0.0,29.0,0.0
75%,6.0,140.0,80.0,32.0,126.0,36.0,1.0,41.0,1.0
max,17.0,199.0,122.0,99.0,846.0,67.0,2.0,81.0,1.0

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
df["Outcome"].value_counts()

Outcome
0    502
1    270
Name: count, dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(4)

In [ ]:
df.drop_duplicates()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35.0,0,33.6,0.627,50,1
1,1,85,66,29.0,0,26.6,0.351,31,0
2,8,183,64,0.0,0,23.3,0.672,32,1
3,1,89,66,23.0,94,28.1,0.167,21,0
4,0,137,40,35.0,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48.0,180,32.9,0.171,63,0
764,2,122,70,27.0,0,36.8,0.340,27,0
765,5,121,72,23.0,112,26.2,0.245,30,0
766,1,126,60,0.0,0,30.1,0.349,47,1
767,1,93,70,31.0,0,30.4,0.315,23,0

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               2
Insulin                     0
BMI                         7
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
x=df["BMI"].mean()
df["BMI"].fillna(x, inplace=True)

/tmp/ipython-input-168-193794204.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["BMI"].fillna(x, inplace=True)

In [ ]:
# df["BMI"].fillna(0, inplace=True)

In [ ]:
df.dropna(subset=["SkinThickness"], inplace=True)

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
#to delete column
# df.drop("SkinThickness", axis=1, inplace=True)

In [ ]:
df[(df["Glucose"]>190)]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
8,2,197,70,45.0,543,30.5,0.158,53,1
22,7,196,90,0.0,0,39.8,0.451,41,1
185,7,194,68,28.0,0,35.9,0.745,41,1
206,8,196,76,29.0,280,37.5,0.605,57,1
228,4,197,70,39.0,744,36.7,2.329,31,0
258,1,193,50,16.0,375,25.9,0.655,24,0
260,3,191,68,15.0,130,30.9,0.299,34,0
319,6,194,78,0.0,0,23.5,0.129,59,1
359,1,196,76,36.0,249,36.5,0.875,29,1
399,3,193,70,31.0,0,34.9,0.241,25,1
408,8,197,74,0.0,0,25.9,1.191,39,1
489,8,194,80,0.0,0,26.1,0.551,67,0
498,7,195,70,33.0,145,25.1,0.163,55,1
561,0,198,66,32.0,274,41.3,0.502,28,1
579,2,197,70,99.0,0,34.7,0.575,62,1
661,1,199,76,43.0,0,42.9,1.394,22,1
675,6,195,70,0.0,0,30.9,0.328,31,1

In [ ]:
df.sort_values(by="Glucose", ascending=False)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
661,1,199,76,43.0,0,42.9,1.394,22,1
561,0,198,66,32.0,274,41.3,0.502,28,1
579,2,197,70,99.0,0,34.7,0.575,62,1
408,8,197,74,0.0,0,25.9,1.191,39,1
228,4,197,70,39.0,744,36.7,2.329,31,0
...,...,...,...,...,...,...,...,...,...
342,1,0,68,35.0,0,32.0,0.389,22,0
349,5,0,80,32.0,0,41.0,0.346,37,1
182,1,0,74,20.0,23,27.7,0.299,21,0
502,6,0,68,41.0,0,39.0,0.727,41,1
75,1,0,48,20.0,0,24.7,0.140,22,0

In [ ]:
df["Outcome"].unique()

array([1, 0])

In [ ]:
df["Outcome"].nunique()

2

In [ ]:
data = pd.read_csv('/content/Salary_Data.csv')
data.head()

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [ ]:
data1 = pd.concat([df , data])

In [ ]:
data1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,YearsExperience,Salary
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333,1.0,NaN,NaN
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667,0.0,NaN,NaN
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333,1.0,NaN,NaN
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000,0.0,NaN,NaN
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,105582.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.5,116969.0
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.6,112635.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.3,122391.0
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.5,121872.0

In [ ]:
data2 = pd.concat([df , data], axis=1)

In [ ]:
data2

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,YearsExperience,Salary
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333,1.0,1.1,39343.0
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667,0.0,1.3,46205.0
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333,1.0,1.5,37731.0
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000,0.0,2.0,43525.0
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000,1.0,2.2,39891.0
...,...,...,...,...,...,...,...,...,...,...,...
765,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333,0.0,NaN,NaN
766,0.058824,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.433333,1.0,NaN,NaN
767,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333,0.0,NaN,NaN
768,0.058824,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.433333,1.0,NaN,NaN
769,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333,0.0,NaN,NaN

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333,1.0
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667,0.0
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333,1.0
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000,0.0
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000,1.0

In [ ]:
data3 = pd.concat([df , df])

In [ ]:
data3

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333,1.0
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667,0.0
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333,1.0
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000,0.0
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000,1.0
...,...,...,...,...,...,...,...,...,...
765,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333,0.0
766,0.058824,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.433333,1.0
767,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333,0.0
768,0.058824,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.433333,1.0
769,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333,0.0